apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-hello-world
  namespace: default
  labels:
    app.kubernetes.io/part-of: python-hello-world
    apps.tanzu.vmware.com/workload-type: python
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/Turbots/python-hello-world.git